config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#index"
  # get '/admin', to: 'users#admin', as: :admin_panel
  get "/sessions/new", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"
  get "/friendships/:id/confirm", to: "friendships#confirm", as: "confirm_friendship"
   get "/friendships/:id/deny", to: "friendships#deny", as: "deny_friendship"

  resources :users
  resources :messages
  resources :friendships
  resources :document_accesses
  resources :documents
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :friendship
  serialize :data
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authorize_user

    def show
        @messages = Message.all.where(friendship_id: params[:id])
        if @messages.count == 0; @messages = nil; end
        @friend = Friendship.all.where(id: params[:id]).first
        if @friend.user_id != current_user.id
            @friend = @friend.user
        else
            @friend = @friend.friend_user
        end
    end

    def new
        @friend = User.all.where(id: params[:format]).first
    end
    
    def create
        @message = Message.new
        @friend = User.all.where(id: params[:format]).first
        friendship_id = Friendship.all.where("user_id = ? AND friend_user_id = ? OR user_id = ? AND friend_user_id = ?", current_user.id, @friend.id, @friend.id, current_user.id).first.id
        @message.friendship_id = friendship_id
        @message.data = []
        @message.data.push({current_user => params[:data]})
        @message.save
        # if @message.data.first.values.first != 0
        # end
        redirect_to edit_message_path(@message)
    end

    def edit
        @message = Message.all.where(id: params[:id]).first
        friendship = Friendship.all.where(id: @message.friendship_id).first
        if friendship.user != current_user
            @friend = friendship.user
        else
            @friend = friendship.friend_user
        end
    end
    
    def update
        @message = Message.all.where(id: params[:id]).first
        @message.data.push({current_user => params[:data]})
        @message.save
        redirect_to edit_message_path
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/edit.html.erb
<h1>Conversation <%= @message.id%> with <%= @friend.first_name%></h1>

<% @message.data.each do |transaction|%>

<% if transaction.first.first == @friend %>
<h3 style='float:right'><%= transaction.first.second %> :<%= transaction.first.first.first_name %></h3><br><br><br><br>
<%elsif transaction.first.first == current_user %>
<h3 style='float:left'><%= transaction.first.first.first_name %>: <%= transaction.first.second %></h3><br><br><br><br>
<% end %>
<% end %>

<%= form_tag message_path, method: :patch do %>
<%= label_tag :data %>
<%= text_field_tag :data %>
<%= submit_tag 'Submit Post' %>
<% end %>

<%= link_to 'Back', friendships_path%>

app/views/messages/new.html.erb
<h1>New conversation with <%= @friend.first_name%></h1>

<%= form_tag messages_path(@friend) do %>
<%= label_tag :data %>
<%= text_field_tag :data %>
<%= submit_tag 'Submit Post' %>

<% end %>

app/views/messages/show.html.erb
<h1><%= @friend.first_name%>s' Messages</h1>

<%if @messages != nil%>
<dl>
<%@messages.each do |message| %>

<dt>Conversation <%= link_to message.id, edit_message_path(message) %></dt>
<dd> <%= message.data[-1].values.first.slice(0, 10) + '...'%> </dd>

<% end %>
</dl>
<% else %>
    <h1>You have no messages with <%= @friend.first_name %> yet!</h1>
<% end %>
<%= link_to 'New Message', new_message_path(@friend) %>