config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#index"
  # get '/admin', to: 'users#admin', as: :admin_panel
  get "/sessions/new", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"
  get "/friendships/:id/confirm", to: "friendships#confirm", as: "confirm_friendship"
   get "/friendships/:id/deny", to: "friendships#deny", as: "deny_friendship"

  resources :users
  resources :messages
  resources :friendships
  resources :document_accesses
  resources :documents
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :document_access, dependent: :destroy

    has_many :documents, through: :document_access, dependent: :destroy

    # has_many :friendships, foreign_key: 'user'
    # has_many :friendships, foreign_key: 'friend_user'
    has_many :friendships, ->(user) { where('user_id = ? OR friend_user_id = ?', user.id, user.id)}, dependent: :destroy

    has_many :users, through: :friendships, foreign_key: 'friend_user', dependent: :destroy

    has_many :messages, through: :friendships, dependent: :destroy


    has_secure_password

    validates :first_name, :last_name,  presence: true
    validates :last_name,  presence: true
    validates :username, presence: true , uniqueness: true 
    validates :password, presence: true
    validates :password, length: { in: 4..20 }
    validates :username, length: { in: 3..20 }

    def find_potential
        no_friends = User.all.select{|user| user.friendships.count == 0}
        not_mine = Friendship.all.where("user_id != ? OR friend_user_id != ?", self.id, self.id)
        array =[]
        not_mine.each do |obj| 
            array.push(obj.user)
            array.push(obj.friend_user)
        end
        no_friends.union(array)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  


  def admin
    authorize_user
  end

  def index
    authorize_user
    @users = User.all
    @friendships = Friendship.all
  end

  def show
    authorize_user
    @user = User.find(params[:id])
    
  end

  def new
    @user = User.new
  end

  def edit 
    authorize_user
    @user = User.find(params[:id])
  end

  def create 
     user = User.new(user_params)
      if user.valid?
        user.save
        session[:user_id] = user.id
        redirect_to user
      else
        flash[:errors] = user.errors.full_messages
        redirect_to new_user_path
      end
    end

    def update 
        authorize_user
        user = User.find(params[:id])
        user.first_name = user_params[:first_name]
        user.last_name = user_params[:last_name]
        user.username = user_params[:username]
        user.password = user_params[:password]
        if user.valid?
          user.save
          redirect_to user_path(user)
        else
          flash[:errors] = user.errors.full_messages
          render :edit 
        end
      end




    private
    
    def user_params 
      params.require(:user).permit(:first_name, :last_name, :username , :password, admin?: false)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <% if flash[:errors] %>
      <div style="color: red;">
      <% flash[:errors].each do |message| %>
          <p><%= message %></p>
      <% end %>
      </div>
      <% end %>

<%= form_for(@user) do |f| %>
<%=f.label 'First Name'%><br>
<%= f.text_field :first_name%><br><br>
<%=f.label 'Last Name'%><br>
<%= f.text_field :last_name%><br><br>
<%=f.label 'Username'%><br>
<%= f.text_field :username%><br><br>
<%=f.label 'Password'%><br>
<%= f.password_field :password_digest%><br><br>
<%=f.label 'Confirm Password'%><br>
<%= f.password_field :password%><br><br><br>

<%= f.submit%>

<% end %>

app/views/users/admin.html.erb
<h1> ADMIN </h1>

app/views/users/edit.html.erb
<h1>Editing User</h1>

  <% if flash[:errors] %>
      <div style="color: red;">
      <% flash[:errors].each do |message| %>
          <p><%= message %></p>
      <% end %>
      </div>
      <% end %>

<%= form_for(current_user) do |f| %>
<%=f.label 'First Name'%><br>
<%= f.text_field :first_name%><br><br>
<%=f.label 'Last Name'%><br>
<%= f.text_field :last_name%><br><br>
<%=f.label 'Username'%><br>
<%= f.text_field :username%><br><br>
<%=f.label 'Password'%><br>
<%= f.password_field :password_digest%><br><br>
<%=f.label 'Confirm Password'%><br>
<%= f.password_field :password%><br><br><br>

<%= f.submit%>

<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>All Doczers</h1>
fix the send request <br>

<% @users.each do |user|%>
<% if current_user != user %>
<tr>
 <td><%= link_to user.username, user %></td>
<%else%>
 <% end %>
</tr>
<% end %>

app/views/users/new.html.erb
<p> Already have an account? </p>

<% if flash[:errors] %>
      <div style="color: red;">
      <% flash[:errors].each do |message| %>
          <p><%= message %></p>
      <% end %>
      </div>
      <% end %>

<h1>SIGN UP</h1>
  
<%= form_for @user do |f| %>
<%=f.label 'First Name'%><br>
<%= f.text_field :first_name%><br><br>
<%=f.label 'Last Name'%><br>
<%= f.text_field :last_name%><br><br>
<%=f.label 'Username'%><br>
<%= f.text_field :username%><br><br>
<%=f.label 'Password'%><br>
<%= f.password_field :password_digest%><br><br>
<%=f.label 'Confirm Password'%><br>
<%= f.password_field :password%><br><br><br>

<%= f.submit 'Create'%>

<% end %><br>

app/views/users/show.html.erb
  
<p id="notice"><%= notice %></p>
<h1>Welcome  <%=@user.first_name%> !</h1>
<h2>You are logged in as <%= @user.username %></h2>

<div><h4>My Docz</h4>
<ul>
<% @user.documents.each do |doc|%>
<li> <%= link_to doc.data.html_safe[0..10] +"...", doc%></li>
<%end%>
</ul>
<h4>Public Docs:</h4>
<ul>
<% Document.all.each do |doc|%>
   <% if doc.public? %>
<li> <%= link_to doc.data.html_safe[0..10] +"...", doc%></li>
    <% end %>
<%end%>
</ul>
</div>

<h4><%= link_to  "Create a Document", new_document_path%></h4>

<%= link_to 'Update My Details', edit_user_path(@user) %><br>
<%= link_to 'Friends', friendships_path %>