config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#index"
  # get '/admin', to: 'users#admin', as: :admin_panel
  get "/sessions/new", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"
  get "/friendships/:id/confirm", to: "friendships#confirm", as: "confirm_friendship"
   get "/friendships/:id/deny", to: "friendships#deny", as: "deny_friendship"

  resources :users
  resources :messages
  resources :friendships
  resources :document_accesses
  resources :documents
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :friend_user, class_name: 'User', foreign_key: 'friend_user_id'
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
    has_many :document_access, dependent: :destroy

    has_many :documents, through: :document_access, dependent: :destroy

    # has_many :friendships, foreign_key: 'user'
    # has_many :friendships, foreign_key: 'friend_user'
    has_many :friendships, ->(user) { where('user_id = ? OR friend_user_id = ?', user.id, user.id)}, dependent: :destroy

    has_many :users, through: :friendships, foreign_key: 'friend_user', dependent: :destroy

    has_many :messages, through: :friendships, dependent: :destroy


    has_secure_password

    validates :first_name, :last_name,  presence: true
    validates :last_name,  presence: true
    validates :username, presence: true , uniqueness: true 
    validates :password, presence: true
    validates :password, length: { in: 4..20 }
    validates :username, length: { in: 3..20 }

    def find_potential
        no_friends = User.all.select{|user| user.friendships.count == 0}
        not_mine = Friendship.all.where("user_id != ? OR friend_user_id != ?", self.id, self.id)
        array =[]
        not_mine.each do |obj| 
            array.push(obj.user)
            array.push(obj.friend_user)
        end
        no_friends.union(array)
    end


end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    before_action :authorize_user

    def index
        @friendships = Friendship.all.where("user_id = ? OR friend_user_id = ?", current_user.id, current_user.id)
        @friendships = @friendships.select{|f| f.confirmed?}
    end

    def new
        @friendship = Friendship.new
        @potential_friends = current_user.find_potential
        requests = Friendship.all.where("friend_user_id = ?", current_user.id)
        @requests = requests.select{|e| !e[:confirmed?]}
    end

    def show 
        @friendship = Friendship.find(params[:id])
    end

    def create
         @friendship = Friendship.create(user_id: current_user.id, friend_user_id: params[:friendship][:friend_user_id], confirmed?: false)
         redirect_to user_path(current_user)
    end

    def confirm
        friend = Friendship.find(params[:id])
        friend.update(confirmed?: true)
        friend.save
        redirect_to new_friendship_path
    end

    def deny
        Friendship.delete(params[:id])
        redirect_to new_friendship_path
    end

    private

    def friendship_params
        params.require(:friendship).permit(:user_id, :friend_user_id, :confirmed?)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<p>My friends:</p>
<% @friendships.each do |friendship| %>

    <% if friendship.confirmed? %>

        <% if friendship.user_id != current_user.id %>
        <% user_name = "#{friendship.user.first_name} #{friendship.user.last_name}" %>
            <p><%= link_to user_name, message_path(friendship) %></p>
        <% else %>
        <% friend_name = "#{friendship.friend_user.first_name} #{friendship.friend_user.last_name}" %>
            <p><%= link_to friend_name, message_path(friendship) %></p>
        <% end %>
    <% end %>
<% end %>
<br>
<p>Send A request to a <%=link_to "doczer", new_friendship_path%></p>

app/views/friendships/new.html.erb
<h1>All Doczers</h1>


  <%= form_tag friendships_path(@friendship) do %>
  
   <%= collection_select :friendship, :friend_user_id, @potential_friends, :id, :username %>
      <%= submit_tag 'Submit Post'%>
   <% end %>


   <%@requests.each do |request|%>

   <p><%=request.user.first_name%> wants to be your friend?</p>
   <%= link_to 'Confirm', confirm_friendship_path(request)%> <%= link_to 'Deny', deny_friendship_path(request)%>
  <% end %>
  <%= link_to 'Back', friendships_path%>

<%
=begin%>
   
<%= form_for @friendship do |f| %>
    <%= f.label  'Choose your friend' %>
    <%= f.collection_select :friendship, @potential_friends :id, :username %>
    <%= f.label :friendships, 'Choose your friends' %>
    <%= f.collection_check_boxes :friendship_ids, @potential_friends, :id, :username %>
    <%= f.submit %>
  <% end %> 
<%
=end%>

app/views/friendships/show.html.erb
one friend


<%=  @friendships %>