config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#index"
  # get '/admin', to: 'users#admin', as: :admin_panel
  get "/sessions/new", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy"
  get "/friendships/:id/confirm", to: "friendships#confirm", as: "confirm_friendship"
   get "/friendships/:id/deny", to: "friendships#deny", as: "deny_friendship"

  resources :users
  resources :messages
  resources :friendships
  resources :document_accesses
  resources :documents
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
    has_many :document_access
    has_many :users, through: :document_access
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    before_action :authorize_user
    def index
        @documents = Document.all
    end

    def show
        @document = Document.find(params[:id])
    end

    def new
        @document = Document.new
    end

    def create
        @document = Document.create(data: params[:data])
        DocumentAccess.create(user_id:current_user.id, document_id:@document.id)
        redirect_to user_path(current_user)
    end

    def edit
        @document = Document.find(params[:id])
    end

    def update
        @document = Document.find(params[:id])
        @document.update(data: params[:document][:data])
        redirect_to document_path
    end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/edit.html.erb
<%= form_for @document do |f| %>
  <%= f.text_area :data %>
  <%= f.submit 'Submit Post' %>
<% end %>
   <script>
        ClassicEditor
            .create( document.querySelector( '#document_data' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>

app/views/documents/index.html.erb
<br>
<% @documents.each do |doc| %>

<%= doc.data.html_safe %>

<% end %>

app/views/documents/new.html.erb
<%= form_tag documents_path do %>
  <%= text_area_tag 'data' %><br>
  <%= submit_tag 'Submit Post' %>
<% end %>
   <script>
        ClassicEditor
            .create( document.querySelector( '#data' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>

app/views/documents/show.html.erb
<h2>Document</h2>
<h4>Data:</h4>
<%= @document.data.html_safe%><br><br>


<%= link_to  "Edit My Document", edit_document_path %><br>
<%= link_to "My Friends", friendships_path %>

<p>You have <%= current_user.documents.count%> documents</p>